### ISSUE TITLE
Continuous track info?

### ISSUE THREAD

**Issue by arkholt** [hvianna/audioMotion.js#11]
Is there a way to have the track info remain on the screen continuously instead of fading away after a few seconds when a track changes, or when I press the keyboard shortcut? If not, could this be added as a feature in a future version?

**Comment by hvianna** [comment]
Currently not, but I'll add an option to customize the display time in the upcoming version.
Thanks for suggesting this!

**Comment by hvianna** [comment]
This is now available in [version 20.12](https://github.com/hvianna/audioMotion.js/releases/tag/v20.12) 🚀
