### ISSUE TITLE
Error when drawing with reflex

### ISSUE THREAD

**Issue by Staijn1** [hvianna/audioMotion.js#12]
Hello there,

First of all, I want to mention how awesome this library is. I've been visualizing input with FFT with p5.js for a while, but got sick of how much code was needed. This looks way better and works better too.
I'm currently working on using this library to create a visualizer in an electron app, which is also using Angular.
This means I really need to change some stuff around. Everything seems to work really well so far, but I can't get the reflection to work.

Im passing the following properties to the audioMotion object:

```
options = {
        // audioCtx: undefined,
        barSpace: 0.1,
        bgAlpha: 0.7,
        fftSize: 8192,
        fillAlpha: 1,
        gradient: 'classic',
        lineWidth: 0,
        loRes: false,
        lumiBars: false,
        maxDecibels: -25,
        maxFreq: 22000,
        minDecibels: -85,
        minFreq: 20,
        mode: 2,
        onCanvasDraw: this.drawCallback.bind(this),
        overlay: false,
        radial: false,
        reflexAlpha: 0.15,
        reflexBright: 1,
        reflexFit: true,
        reflexRatio: 0,
        showBgColor: true,
        showFPS: false,
        showLeds: false,
        showPeaks: true,
        showScale: false,
        showScaleY: false,
        smoothing: 0.7,
        spinSpeed: 0,
        start: true,
    }
```
When I change reflexRatio from 0, as shown here, to anything else, like 0.1, I get an error when the canvas is drawing.
The error I get is:

```
ERROR TypeError: Failed to execute 'setTransform' on 'CanvasRenderingContext2D': 6 arguments required, but only 0 present.
    at AudioMotionAnalyzer._draw (audioMotion-analyzer.js:910)
    at audioMotion-analyzer.js:501
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:28183)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:503)
    at ZoneTask.invoke (zone.js:492)
    at timer (zone.js:3034)
```

Am I doing something wrong or is using reflection in electron/angular not possible?

**Comment by hvianna** [comment]
Hello,

Thank you for reporting this! I'm glad you're enjoying audioMotion 😄 

I just added a fix in the new beta I'm working on. Do you mind trying it?

`npm i audiomotion-analyzer@beta`

It's pretty stable and I expect to release the final v3.0.0 in a couple of weeks or so. Just be aware of some [breaking changes](https://github.com/hvianna/audioMotion-analyzer/tree/develop#about).

**Comment by Staijn1** [comment]
I installed this just now, and obviously my application broke. I went to continue stripping my code so I had no errors left, except this is not possible at the moment. This is because the constructor throws an error. The error is as follows:
```
ERROR TypeError: Cannot read property 'connect' of undefined
    at new AudioMotionAnalyzer (audioMotion-analyzer.js:117)
    at VisualizerTestComponent.push.fpoy.VisualizerTestComponent.ngOnInit (visualizer-test.component.ts:329)
    at callHook (core.js:3405)
    at callHooks (core.js:3375)
    at executeInitAndCheckHooks (core.js:3327)
    at refreshView (core.js:8573)
    at refreshEmbeddedViews (core.js:9665)
    at refreshView (core.js:8582)
    at refreshComponent (core.js:9711)
    at refreshChildComponents (core.js:8355)
```

This is thrown when I execute this:
```
ngOnInit(): void {
const elem = document.getElementById('visualizer');
this.audioMotion = new AudioMotionAnalyzer(
            elem,
            this.options
        );
}```

this.options is the list of options I listed in my original post, did not change any property.

**Comment by hvianna** [comment]
I just published beta.2, would you please give it a try? 🤞

**Comment by Staijn1** [comment]
I tried it out and the reflex is working now! That's awesome. Thank you so much.
I couldn't quickly figure out how to disconnect the output from the microphone, but I just set the volume to 0, to prevent a feedback loop. That also worked.
```
setSource() {
        navigator.mediaDevices.getUserMedia({audio: true, video: false})
            .then(stream => {
                const audioCtx = this.audioMotion.audioCtx;
                const micInput = audioCtx.createMediaStreamSource(stream);
                this.audioMotion.disconnectInput();
                this.audioMotion.connectInput(micInput);
                console.log(this.audioMotion)
            })
            .catch(err => {
                console.error(`Could not change audio source - ${err}`, err);
            });
    }
```
This is what I tried.

Unrelated question: Now dataArray is hidden, can you maybe create some function like getBass, getMed, getHigh etc to get averages ranging from 0 to 255? This will enable me and others to process the FFT information to make really interesting things with. P5.js already has similar functionality.

Anyways, thank you so much for you help, this looks really dope!

**Comment by hvianna** [comment]
> I tried it out and the reflex is working now! That's awesome. Thank you so much.

Awesome! 🥳 Thanks for your help!

> I couldn't quickly figure out how to disconnect the output from the microphone, but I just set the volume to 0, to prevent a feedback loop. That also worked.

You could simply use [`disconnectOutput()`](https://github.com/hvianna/audioMotion-analyzer/tree/develop#disconnectoutput-node-) with no parameters, but for some reason Chromium browsers stop generating analyzer data if I do that, so setting the volume to 0 is what I'm using too.

> Unrelated question: Now dataArray is hidden, can you maybe create some function like getBass, getMed, getHigh etc to get averages ranging from 0 to 255? This will enable me and others to process the FFT information to make really interesting things with. P5.js already has similar functionality.

I'll add that to my to-do list. 😄 Thanks for your feedback!
