### ISSUE TITLE
Can play m3u or a Icecast Stream?

### ISSUE THREAD

**Issue by OrlandoHC** [hvianna/audioMotion.js#2]
Awesome work with AudioMotion.js i think this is not an issue but but i cant play an Icecast Stream in MP3 @ 192 kbps 44.1 KhZ or a m3u playlist with it.

**Comment by hvianna** [comment]
Hello, thank you!

Have you tried this on the demo site, or when running audioMotion in your pc?

A stream URL inside an m3u playlist should work in the file explorer.

For example, create a `radio.m3u` file in your music folder with the following contents:
```
#EXTINF Rádio Federal FM 109.7 MHz
https://icecast2.ufpel.edu.br/live
```

Then just navigate to it in audioMotion's file explorer, add it to the queue and it should play.

It currently won't work in local/file mode, which is the mode used in the demo site or if you open the index.html file directly in your browser, but it's definetely something I can improve! 👍

**Comment by OrlandoHC** [comment]
> Hello, thank you!
> 
> Have you tried this on the demo site, or when running audioMotion in your pc?
> 
> A stream URL inside an m3u playlist should work in the file explorer.
> 
> For example, create a `radio.m3u` file in your music folder with the following contents:
> 
> ```
> #EXTINF Rádio Federal FM 109.7 MHz
> https://icecast2.ufpel.edu.br/live
> ```
> 
> Then just navigate to it in audioMotion's file explorer, add it to the queue and it should play.
> 
> It currently won't work in local/file mode, which is the mode used in the demo site or if you open the index.html file directly in your browser, but it's definetely something I can improve! 👍

![2019-09-28 19_54_19-Window](https://user-images.githubusercontent.com/10369992/65824163-d9f8ab80-e229-11e9-884f-2f4086f4802b.png)

Does'nt Work with a normal m3u file (Image Attached), mp3 and the most common audio extensions works properly, the streams in the m3u files are in mp3 format, congratulations for this awesome project. 

Greetings from México.

**Comment by OrlandoHC** [comment]
![2019-09-28 20_11_55-Window](https://user-images.githubusercontent.com/10369992/65824303-41aff600-e22c-11e9-8ede-8e519f5ea765.png)

localhost instance works well with any m3u file! Image Attached

**Comment by hvianna** [comment]
> Does'nt Work with a normal m3u file (Image Attached), mp3 and the most common audio extensions works properly, the streams in the m3u files are in mp3 format, congratulations for this awesome project.

> 
> localhost instance works well with any m3u file! Image Attached

Thanks again for the feedback! That's about right, uploaded files are just loaded directly into the audio element as a blob. I'm not parsing their contents, so playlists won't work.

For the demo site, I'll add another field to allow loading remote files or streams via URL. This will be in v19.10, to be released later this month.

I just released my spectrum analyzer as a standalone JS module and added this feature to the demos [here](https://hvianna.github.io/audioMotion-analyzer/demo/fluid.html) and [here](https://hvianna.github.io/audioMotion-analyzer/demo/multi.html).

Saludos from Brasil! :raising_hand_man:

**Comment by hvianna** [comment]
As of [version 19.10](https://github.com/hvianna/audioMotion.js/releases/tag/v19.10) it is now possible to load remote files and audio streams via URL, while running audioMotion in file mode.

**Comment by JesusGod-Pope666-Info** [comment]
I tried downloading multiple radio files from a place although half of them did not sure up as they where not m3u, but sadly non of the m3u worked. I thought it was just the player not working but then I downloaded the 5 you have on your demo, 3 of them being online and they worked.

So... Not sure why the others did not work, but I have deleted them.

**Comment by JesusGod-Pope666-Info** [comment]
Okay I found the m3u files in the Trash and restored them, they work in VLC alright but not in the player. I'll take a look on it now and see if I can a difference.
