### ISSUE TITLE
Microphone input causes "bounce" of display

### ISSUE THREAD

**Issue by MarkerB** [hvianna/audioMotion.js#3]
Amazing work!

If I play a steady tone into the microphone, the display "bounces" something like 3-4 times per second, as if the tone was pulsed.

Is that because live input is sampled in discrete chunks several times a second, and this an artifact of that technique?  Is there a way to improve on this?

**Comment by MarkerB** [comment]
Oops.  Sorry.  This "bouncing" only seems to happen with Firefox.  I'm on Windows 10.  Sorry to bother.

**Comment by hvianna** [comment]
@MarkerB No problem, thank you for reporting!
I'll try to reproduce the issue and see if there's anything I can improve.
