### ISSUE TITLE
no linear scale?

### ISSUE THREAD

**Issue by hsnam95** [hvianna/audioMotion.js#34]
First of all, many thanks for making this wonderful piece.
This has been very useful for an educational purpose, especially to students working on DSP and/or phonetics.
Could you add an option to switch Logarithmic to linear scale? 
This will be really informative in a certain area for sure.
Thanks!!

**Comment by hvianna** [comment]
Linear, Bark and Mel frequency scales are available in the new beta.

The online app can now play music from your hard drive, on Chromium-based browsers.

[Check the release here](https://github.com/hvianna/audioMotion.js/releases/tag/v24.2-beta.0)

**Comment by hvianna** [comment]
Now available in [version 24.3](https://github.com/hvianna/audioMotion.js/releases/tag/v24.3) 🎉
