### ISSUE TITLE
Seems the pictures are not coming forth in the Vizualizer.

### ISSUE THREAD

**Issue by JesusGod-Pope666-Info** [hvianna/audioMotion.js#37]
Well now that I have the Folder search sorted, and things seems to work - but then I found out, that the images, background and front does not seem to appear in the Visualizer... Seems like everything else is working. But am I missing something, the images? Or does it need to have access to something or what?....

Darkijah
![Screenshot_2023-09-21_01-51-47](https://github.com/hvianna/audioMotion.js/assets/90806094/25d9bdc2-68f0-47d6-84e2-8a06fd8a6c34)

**Comment by JesusGod-Pope666-Info** [comment]
Still having issues... I will try the pictures now, there are some options for that. But.... Just unsure as to how to make the background video work, I will download some more and be ready to further testing, I'll try the pictures now, I think I can sort that out from the manual instructions.

**Comment by hvianna** [comment]
You need the `.htaccess` file to enable directory listing in the `backgrounds/` folder as well. 

```apache
Options +Indexes
```

**Comment by JesusGod-Pope666-Info** [comment]
The Problem was I did not know and how it would be done - you should have at least 1 single background of picture and video AND the folder where they are and the .htaccess sorted out. Newbies like me, should not have to toy around to find a working example in apps. I found out what the folder was by finding it on your demo - but....

You can just put the .htaccess with the Options +Indexes in the root by the way and things seems to work. That was not the problem I had this time - the problem for me was to figure out how it functioned.

BUT I think you might have an issue with the small picture which probably is some code that links for an image that my Gnulix browsers does not have, I have the same issue in my Media Player on my website that I need to sort out.

![Screenshot_2023-09-23_21-36-41](https://github.com/hvianna/audioMotion.js/assets/90806094/15f26eb8-124e-4f9f-a9e0-a7dbd4542650)

**Comment by JesusGod-Pope666-Info** [comment]
And further with the backgrounds folder, you should have a music folder as well prepared. Like just have a very small sound file in it and the same in the backgrounds folder - just for easy understanding of people who begins to use it. No overkill, just so we can see how it function without using hours and hours to sort out things. Or at the very least have the manual say how it works - like backgrounds?.... I could not find anything.... just.... trying to figure things out.

Some minor and small examples would save people from a lot of waste of time. 1 images background, 1 video background in the already made folder - and one mp3 file in the already made music folder. Could save people from wasting hours to figure it out.

Anyway, so far so good.

**Comment by JesusGod-Pope666-Info** [comment]
By the way, you know what code in m3u that makes the 3 line in your apps????? I can only figure out the 2 first lines but clearly there is a 3 one.

**Comment by hvianna** [comment]
> The Problem was I did not know and how it would be done - you should have at least 1 single background of picture and video AND the folder where they are and the .htaccess sorted out.

Yeah, I'll try and improve that in the next release.
 
> BUT I think you might have an issue with the small picture which probably is some code that links for an image that my Gnulix browsers does not have, I have the same issue in my Media Player on my website that I need to sort out.

The small images are emojis. It should be standard in any modern operating system. You may need to install a system font that supports emojis.

> By the way, you know what code in m3u that makes the 3 line in your apps????? I can only figure out the 2 first lines but clearly there is a 3 one.

If you mean the album name and year, that info is obtained from the audio metadata. Some files include it, some don't. 

There is a non-standard #EXTALB: directive in the [m3u format](https://en.wikipedia.org/wiki/M3U), but my code does not parse for it yet. I may include support for it in a future release.

**Comment by JesusGod-Pope666-Info** [comment]
Yea I have emojis issues other places, and would be nice to just have them in the app so this is not an issue. Overall the more that is kept inside the app, the less can be broken by trying to get things outside which is not always there, like now. I have the same issue with my webpage, and further different browsers makes different pictures for the & kinda of code, which has some kind of name. Sorta a little of the same although I think it is still different although not sure if there is a connection between them. I have yet to figure out a way to replace to small pictures and copy them, not sure where I can find the images I want - although I could just take a screenshot and sort it out in an image editor.

I will try doing a search for emojis in the system, but really, would be nice if you just made them stick in the app, it is not much data anyway if you know how to do that easy. And then you get the emojis you want as well for the app. But maybe the idea is the ability to change them by the system theme or something?....

Yea I tried all the Album codes I could without any result, if you could have something that seeks it out, one could use it for maybe Radio Webpage and further info or something. Still trying to sort out how to best do it, but it would be nice to have the ability at least with the 3 line. So please include some kind of support for it. The Ability is clearly there as seen from other files, and even sending info from the radio station is possible for it clearly. Just need some kind of knowlegde as to how to do it in the m3u file directly :)

**Comment by JesusGod-Pope666-Info** [comment]
Not sure... but your demo seems to be faster then the one I have installed on my page on the low smoothing. Not sure what that is about, anyway... looking forward to your future release.
I have now sorted around 30 working Radio Channels although the information is still a mess and was looking forward to be able to use the 3 line as well. The Album line the name must be.

**Comment by JesusGod-Pope666-Info** [comment]
You want an app to be as locale as possible, as to be as portable as possible! :) That is the way to go for freedom and away from Tyrannic strings which keeps us locked. Sadly computing took the other direction pushed by the big guys who think they deserve to steer the ship and sink it as much as possible while doing it.

**Comment by JesusGod-Pope666-Info** [comment]
found the data:
![Screenshot_2023-09-25_12-04-31](https://github.com/hvianna/audioMotion.js/assets/90806094/c96271c1-98f8-4c84-b1d5-d2e4c34a64a0)
![Screenshot_2023-09-25_12-05-23](https://github.com/hvianna/audioMotion.js/assets/90806094/9db7ed31-e374-4c42-a31d-55563aafc0bd)

**Comment by JesusGod-Pope666-Info** [comment]
Yea lets get a parsing on the album, i get loading of it for the m3u files would be nice. It could be used for the Webpage data or something of that kind.
