### ISSUE TITLE
Issue with radio files.

### ISSUE THREAD

**Issue by JesusGod-Pope666-Info** [hvianna/audioMotion.js#38]
So I downloaded a bunch of m3u files from a page somewhere, now they do seem to work in the VLC player but wont play in the audioMotion player. Not sure what is wrong, I thought my player just did not work with it, but as I downloaded your own in the demo and tested them, I found out it actually worked on those 3 live ones that usually works.

![Screenshot_2023-09-21_09-38-06](https://github.com/hvianna/audioMotion.js/assets/90806094/e0e4c02a-e685-4021-b06a-74682c8d39bf)

Not sure what is wrong or different, I see if I can check the with the txt app and see if there is something.

---- Darkijah

**Comment by JesusGod-Pope666-Info** [comment]
Might be a https issue or... there are some options... Lets see if I can get things to work.

**Comment by JesusGod-Pope666-Info** [comment]
Nope... I can't seem to figure out what is wrong. If it is my host blogging something maybe or the player that have some issues with these m3u files... tried to copy the url into it by the app, the one I know working the one I know does not, although it is live working in VLC and on the page it links to.

I don't know, here is the link for one: http://us1.internet-radio.com:8107

**Comment by hvianna** [comment]
yeah, that's another JavaScript security mechanism, called CORS. If the server doesn't explicitly allow access from outside domains, you can't access the file/stream.

**Comment by JesusGod-Pope666-Info** [comment]
Ahh yea, all the security bullshit of this mad world of censorship.
I found a way to find the URL to the streams by the way by Chrome which seems to be pretty effective, IF the source plays and it not censored by bullshit.

So sickening with all the censorship of country.

Maybe I can now circumvent it - http://us1.internet-radio.com:8107/stream2?type=http&nocache=245 ;)

**Comment by JesusGod-Pope666-Info** [comment]
Jup that worked! until they change the URL.
![Screenshot_2023-09-23_21-25-08](https://github.com/hvianna/audioMotion.js/assets/90806094/c381fc06-139f-4967-bb01-3835b671510b)

Sadly I deleted those that did not work. But anyway.... Hack the planet, that is all one tend to feel to do these days.

**Comment by JesusGod-Pope666-Info** [comment]
Although the Radio stations that is banned in my nation - I will need some kind of VPN of nation which I don't have the moment.
I knew of one that I used that gave you a specific amount of time from whatever nation - just need a minute or so and Chrome inspect tool, network and control r and there you go. But so sick and tired of the nonsense and waste of time they commit us to.

**Comment by JesusGod-Pope666-Info** [comment]
![Screenshot_2023-09-23_21-29-54](https://github.com/hvianna/audioMotion.js/assets/90806094/f96530f1-f118-433d-a389-1b6a84c27909)

**Comment by JesusGod-Pope666-Info** [comment]
Things like this tend to piss me off.... I'm so sick and tired of feeling like I'm hacking everything to get things to do what I want.
![Screenshot_2023-09-23_21-57-27](https://github.com/hvianna/audioMotion.js/assets/90806094/6eac39c2-3c1e-46a0-a0a3-ddb0372ca3e1)

The one station I talked to, said they wanted everybody to listen to there radio station and it was not them blocking - I have now found out it is the overall web page that blocks me. Give me a break, so I can't even play a small amount to catch the source, but will need a VPN telling it that I am from the US or something of that kind.

**Comment by JesusGod-Pope666-Info** [comment]
Here you can see the 3 line of information, how do I do that in a m3u file?
![Screenshot_2023-09-23_22-26-40](https://github.com/hvianna/audioMotion.js/assets/90806094/2ab7fd83-2b8a-432e-829e-8d7cb3fdad21)

**Comment by JesusGod-Pope666-Info** [comment]
I have around 50 m3u files here, and pretty much every one of them work in VLC, yet not in the audioMotion, it might be some security but.... should be able to bypass that so it works like in VLC without needing to use time on fixing it?

**Comment by JesusGod-Pope666-Info** [comment]
Everything they could they did to make it hard, it feels like. Both from one side and the other on this radio stuff. The exact opposite of what should have been done. But that is today's wicked world.
