### ISSUE TITLE
cannot change font size and the position in "song info"

### ISSUE THREAD

**Issue by kimycai** [hvianna/audioMotion.js#44]
there is no setting to change the font size of “song info” and the position of left track info and the right info，I hope this feature will be added to soon！O(∩_∩)O

**Comment by kimycai** [comment]
<img width="1274" alt="Tray_waifu2x_2x_jpg" src="https://github.com/hvianna/audioMotion.js/assets/17998728/12c98f0f-d9b5-4a6a-a8e6-6e5219592822">
sometime, the artist name will be very long,and stick together to the track time.

**Comment by hvianna** [comment]
Thanks for the suggestions. I'll try to improve this in a future release.

**Comment by hvianna** [comment]
Now available in [version 24.3](https://github.com/hvianna/audioMotion.js/releases/tag/v24.3) 🎉
