### ISSUE TITLE
Can the background be set to be transparent?

### ISSUE THREAD

**Issue by Haojen** [hvianna/audioMotion.js#5]
I need  put  this canvas on a another canvas,  so I need this background is transparent, but I don't know how to set it to a transparent background, I've looked at the documentation, but there seems to be no way to do it.
your project is awesome,  thank you build it!

**Comment by hvianna** [comment]
Currently there's no way to do this, but it's definetely something I can try and implement in the [audioMotion-analyzer](https://github.com/hvianna/audioMotion-analyzer) module.

Thanks for the feedback and suggestion!

**Comment by Haojen** [comment]
> Currently there's no way to do this, but it's definetely something I can try and implement in the [audioMotion-analyzer](https://github.com/hvianna/audioMotion-analyzer) module.
> 
> Thanks for the feedback and suggestion!

Yep, I'm using it right now `audiomotion-analyzer`, thank you reply me, and I really like this project. but for Now, I must use some another SDK to keep canvas background is  transparent, this is  so sad, I wish can be soon use your SDK

**Comment by hvianna** [comment]
This is now available in [audioMotion-analyzer v2.2.0](https://github.com/hvianna/audioMotion-analyzer/releases/tag/2.2.0) 🎊
