### ISSUE TITLE
FEATURE REQUEST: Circular Audio Spectrum 

### ISSUE THREAD

**Issue by inglesuniversal** [hvianna/audioMotion.js#6]
Suggestion based on this YouTube Video:

[https://www.youtube.com/watch?v=QeNHHIjgvHU](url)

**Comment by hvianna** [comment]
[Radial](https://github.com/hvianna/audioMotion.js/blob/master/docs/user-interface.md#mode-switches) visualization is now available in [v20.8](https://github.com/hvianna/audioMotion.js/releases/tag/v20.8) :tada:

**Comment by inglesuniversal** [comment]
YOU DID IT!!!

I just checked the UPDATE and it looks out of this world!!!

I am extremely proud that you accepted my humble suggestion to include this improvement, which years ago was only or mainly possible with flash.

Amazing Work!!!!

Take care of yourself and I will keep you up to date of any new or fresh ideas!!!

**Comment by hvianna** [comment]
Awesome, I'm really happy it met your expectations!! 😄 

Take care!
