### ISSUE TITLE
Disable playback of microphone input to speakers

### ISSUE THREAD

**Issue by net147** [hvianna/audioMotion.js#9]
It would be good to have option to disable playback of microphone input to speakers to avoid feedback loops.

**Comment by net147** [comment]
Probably makes sense to me to disable playback of microphone input to speakers by default, then have a checkbox to enable monitoring of microphone input to speakers.

**Comment by hvianna** [comment]
😮 You're right, there doesn't seem to be any reason to connect the microphone to the output, not even for the "stereo mix" mode. I guess nobody (including me) had ever used this option enough! 

Will fix this ASAP. Thanks for spotting this!

**Comment by hvianna** [comment]
Fixed in [version 20.9](https://github.com/hvianna/audioMotion.js/releases/tag/v20.9)
